package CustomerManagement;


/**
* CustomerManagement/_CustomerUpdateServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public class _CustomerUpdateServiceStub extends org.omg.CORBA.portable.ObjectImpl implements CustomerManagement.CustomerUpdateService
{

  public boolean updateCustomerInfo (CustomerManagement.CustomerInfo customer)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerInfo", true);
                CustomerManagement.CustomerInfoHelper.write ($out, customer);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerInfo (customer        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerInfo

  public boolean updateCustomerStatus (String customerId, String customerStatus)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerStatus", true);
                $out.write_string (customerId);
                $out.write_string (customerStatus);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerStatus (customerId, customerStatus        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerStatus

  public boolean updateCustomerType (String customerId, String customerType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerType", true);
                $out.write_string (customerId);
                $out.write_string (customerType);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerType (customerId, customerType        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerType

  public boolean updateCustomerAddress (String customerId, String customerAddress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerAddress", true);
                $out.write_string (customerId);
                $out.write_string (customerAddress);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerAddress (customerId, customerAddress        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerAddress

  public boolean updateCustomerPhone (String customerId, String customerPhone)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerPhone", true);
                $out.write_string (customerId);
                $out.write_string (customerPhone);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerPhone (customerId, customerPhone        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerPhone

  public boolean updateCustomerEmail (String customerId, String customerEmail)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerEmail", true);
                $out.write_string (customerId);
                $out.write_string (customerEmail);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerEmail (customerId, customerEmail        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerEmail

  public boolean updateCustomerName (String customerId, String customerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateCustomerName", true);
                $out.write_string (customerId);
                $out.write_string (customerName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateCustomerName (customerId, customerName        );
            } finally {
                _releaseReply ($in);
            }
  } // updateCustomerName

  public CustomerManagement.UpdateHistory[] getCustomerUpdateHistory (String customerId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCustomerUpdateHistory", true);
                $out.write_string (customerId);
                $in = _invoke ($out);
                CustomerManagement.UpdateHistory $result[] = CustomerManagement.UpdateHistoryListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCustomerUpdateHistory (customerId        );
            } finally {
                _releaseReply ($in);
            }
  } // getCustomerUpdateHistory

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CustomerManagement/CustomerUpdateService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "CustomerManagement._CustomerUpdateServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CustomerUpdateServiceStub
