package CustomerManagement;


/**
* CustomerManagement/ComplaintInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class ComplaintInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String complaintId = null;
  public String customerId = null;
  public String complaintType = null;
  public String complaintInfo = null;
  public String complaintStatus = null;
  public String createdDate = null;
  public String resolutionDate = null;

  public ComplaintInfo ()
  {
  } // ctor

  public ComplaintInfo (String _complaintId, String _customerId, String _complaintType, String _complaintInfo, String _complaintStatus, String _createdDate, String _resolutionDate)
  {
    complaintId = _complaintId;
    customerId = _customerId;
    complaintType = _complaintType;
    complaintInfo = _complaintInfo;
    complaintStatus = _complaintStatus;
    createdDate = _createdDate;
    resolutionDate = _resolutionDate;
  } // ctor

} // class ComplaintInfo
