package CustomerManagement;


/**
* CustomerManagement/CustomerSupportServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public interface CustomerSupportServiceOperations 
{
  boolean createSupportRequest (CustomerManagement.SupportRequest request);
  boolean updateSupportRequest (CustomerManagement.SupportRequest request);
  CustomerManagement.SupportRequest getSupportRequestById (String requestId);
  CustomerManagement.SupportRequest[] getAllSupportRequests ();
  CustomerManagement.SupportRequest[] getSupportRequestsByCustomer (String customerId);
  CustomerManagement.SupportRequest[] getSupportRequestsByStatus (String status);
  String createComplaint (CustomerManagement.ComplaintInfo complaint);
  boolean updateComplaint (CustomerManagement.ComplaintInfo complaint);
  CustomerManagement.ComplaintInfo getComplaintById (String complaintId);
  CustomerManagement.ComplaintInfo[] getAllComplaints ();
  CustomerManagement.ComplaintInfo[] getComplaintsByCustomer (String customerId);
  CustomerManagement.ComplaintInfo[] getComplaintsByStatus (String status);
} // interface CustomerSupportServiceOperations
