package CustomerManagement;


/**
* CustomerManagement/CustomerUpdateServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public interface CustomerUpdateServiceOperations 
{
  boolean updateCustomerInfo (CustomerManagement.CustomerInfo customer);
  boolean updateCustomerStatus (String customerId, String customerStatus);
  boolean updateCustomerType (String customerId, String customerType);
  boolean updateCustomerAddress (String customerId, String customerAddress);
  boolean updateCustomerPhone (String customerId, String customerPhone);
  boolean updateCustomerEmail (String customerId, String customerEmail);
  boolean updateCustomerName (String customerId, String customerName);
  CustomerManagement.UpdateHistory[] getCustomerUpdateHistory (String customerId);
} // interface CustomerUpdateServiceOperations
