package CustomerManagement;


/**
* CustomerManagement/CustomerInfoServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public interface CustomerInfoServiceOperations 
{
  boolean storeCustomerInfo (CustomerManagement.CustomerInfo customer);
  boolean storeTransactionInfo (CustomerManagement.TransactionInfo transaction);
  CustomerManagement.CustomerInfo getCustomerById (String customerId);
  CustomerManagement.CustomerInfo[] getAllCustomers ();
  CustomerManagement.CustomerInfo[] getCustomersByType (String customerType);
  CustomerManagement.CustomerInfo[] getCustomersByRegion (String customerRegion);
  CustomerManagement.CustomerInfo[] getCustomersByStatus (boolean customerStatus);
  CustomerManagement.CustomerInfo[] searchCustomers (String searchTerm);
  CustomerManagement.TransactionInfo[] getCustomerTransactions (String customerId);
  void deleteCustomer (String customerId);
} // interface CustomerInfoServiceOperations
