package CustomerManagement;


/**
* CustomerManagement/CustomerInfoServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public abstract class CustomerInfoServicePOA extends org.omg.PortableServer.Servant
 implements CustomerManagement.CustomerInfoServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("storeCustomerInfo", new java.lang.Integer (0));
    _methods.put ("storeTransactionInfo", new java.lang.Integer (1));
    _methods.put ("getCustomerById", new java.lang.Integer (2));
    _methods.put ("getAllCustomers", new java.lang.Integer (3));
    _methods.put ("getCustomersByType", new java.lang.Integer (4));
    _methods.put ("getCustomersByRegion", new java.lang.Integer (5));
    _methods.put ("getCustomersByStatus", new java.lang.Integer (6));
    _methods.put ("searchCustomers", new java.lang.Integer (7));
    _methods.put ("getCustomerTransactions", new java.lang.Integer (8));
    _methods.put ("deleteCustomer", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CustomerManagement/CustomerInfoService/storeCustomerInfo
       {
         CustomerManagement.CustomerInfo customer = CustomerManagement.CustomerInfoHelper.read (in);
         boolean $result = false;
         $result = this.storeCustomerInfo (customer);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CustomerManagement/CustomerInfoService/storeTransactionInfo
       {
         CustomerManagement.TransactionInfo transaction = CustomerManagement.TransactionInfoHelper.read (in);
         boolean $result = false;
         $result = this.storeTransactionInfo (transaction);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CustomerManagement/CustomerInfoService/getCustomerById
       {
         String customerId = in.read_string ();
         CustomerManagement.CustomerInfo $result = null;
         $result = this.getCustomerById (customerId);
         out = $rh.createReply();
         CustomerManagement.CustomerInfoHelper.write (out, $result);
         break;
       }

       case 3:  // CustomerManagement/CustomerInfoService/getAllCustomers
       {
         CustomerManagement.CustomerInfo $result[] = null;
         $result = this.getAllCustomers ();
         out = $rh.createReply();
         CustomerManagement.CustomerInfoListHelper.write (out, $result);
         break;
       }

       case 4:  // CustomerManagement/CustomerInfoService/getCustomersByType
       {
         String customerType = in.read_string ();
         CustomerManagement.CustomerInfo $result[] = null;
         $result = this.getCustomersByType (customerType);
         out = $rh.createReply();
         CustomerManagement.CustomerInfoListHelper.write (out, $result);
         break;
       }

       case 5:  // CustomerManagement/CustomerInfoService/getCustomersByRegion
       {
         String customerRegion = in.read_string ();
         CustomerManagement.CustomerInfo $result[] = null;
         $result = this.getCustomersByRegion (customerRegion);
         out = $rh.createReply();
         CustomerManagement.CustomerInfoListHelper.write (out, $result);
         break;
       }

       case 6:  // CustomerManagement/CustomerInfoService/getCustomersByStatus
       {
         boolean customerStatus = in.read_boolean ();
         CustomerManagement.CustomerInfo $result[] = null;
         $result = this.getCustomersByStatus (customerStatus);
         out = $rh.createReply();
         CustomerManagement.CustomerInfoListHelper.write (out, $result);
         break;
       }

       case 7:  // CustomerManagement/CustomerInfoService/searchCustomers
       {
         String searchTerm = in.read_string ();
         CustomerManagement.CustomerInfo $result[] = null;
         $result = this.searchCustomers (searchTerm);
         out = $rh.createReply();
         CustomerManagement.CustomerInfoListHelper.write (out, $result);
         break;
       }

       case 8:  // CustomerManagement/CustomerInfoService/getCustomerTransactions
       {
         String customerId = in.read_string ();
         CustomerManagement.TransactionInfo $result[] = null;
         $result = this.getCustomerTransactions (customerId);
         out = $rh.createReply();
         CustomerManagement.TransactionInfoListHelper.write (out, $result);
         break;
       }

       case 9:  // CustomerManagement/CustomerInfoService/deleteCustomer
       {
         String customerId = in.read_string ();
         this.deleteCustomer (customerId);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CustomerManagement/CustomerInfoService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerInfoService _this() 
  {
    return CustomerInfoServiceHelper.narrow(
    super._this_object());
  }

  public CustomerInfoService _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerInfoServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerInfoServicePOA
