package CustomerManagement;


/**
* CustomerManagement/CustomerUpdateService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public interface CustomerUpdateService extends CustomerUpdateServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CustomerUpdateService
