package CustomerManagement;


/**
* CustomerManagement/EmailMetrics.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class EmailMetrics implements org.omg.CORBA.portable.IDLEntity
{
  public String campaignId = null;
  public String emailSent = null;
  public String emailDelivered = null;
  public String emailOpened = null;
  public String emailClicked = null;
  public String emailBounced = null;
  public String emailClickedThroughRate = null;
  public String emailConversionRate = null;

  public EmailMetrics ()
  {
  } // ctor

  public EmailMetrics (String _campaignId, String _emailSent, String _emailDelivered, String _emailOpened, String _emailClicked, String _emailBounced, String _emailClickedThroughRate, String _emailConversionRate)
  {
    campaignId = _campaignId;
    emailSent = _emailSent;
    emailDelivered = _emailDelivered;
    emailOpened = _emailOpened;
    emailClicked = _emailClicked;
    emailBounced = _emailBounced;
    emailClickedThroughRate = _emailClickedThroughRate;
    emailConversionRate = _emailConversionRate;
  } // ctor

} // class EmailMetrics
