package CustomerManagement;

/**
* CustomerManagement/EmailMarketingServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class EmailMarketingServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CustomerManagement.EmailMarketingService value = null;

  public EmailMarketingServiceHolder ()
  {
  }

  public EmailMarketingServiceHolder (CustomerManagement.EmailMarketingService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CustomerManagement.EmailMarketingServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CustomerManagement.EmailMarketingServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CustomerManagement.EmailMarketingServiceHelper.type ();
  }

}
