package CustomerManagement;


/**
* CustomerManagement/EmailCampaign.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class EmailCampaign implements org.omg.CORBA.portable.IDLEntity
{
  public String campaignId = null;
  public String campaignName = null;
  public String campaignType = null;
  public String campaignStatus = null;
  public String campaignSchedule = null;
  public String emailTemplate = null;
  public String targetCustomer = null;

  public EmailCampaign ()
  {
  } // ctor

  public EmailCampaign (String _campaignId, String _campaignName, String _campaignType, String _campaignStatus, String _campaignSchedule, String _emailTemplate, String _targetCustomer)
  {
    campaignId = _campaignId;
    campaignName = _campaignName;
    campaignType = _campaignType;
    campaignStatus = _campaignStatus;
    campaignSchedule = _campaignSchedule;
    emailTemplate = _emailTemplate;
    targetCustomer = _targetCustomer;
  } // ctor

} // class EmailCampaign
