package CustomerManagement;


/**
* CustomerManagement/EmailMetricsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

abstract public class EmailMetricsHelper
{
  private static String  _id = "IDL:CustomerManagement/EmailMetrics:1.0";

  public static void insert (org.omg.CORBA.Any a, CustomerManagement.EmailMetrics that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CustomerManagement.EmailMetrics extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "campaignId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "emailSent",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "emailDelivered",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "emailOpened",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "emailClicked",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "emailBounced",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "emailClickedThroughRate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "emailConversionRate",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CustomerManagement.EmailMetricsHelper.id (), "EmailMetrics", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CustomerManagement.EmailMetrics read (org.omg.CORBA.portable.InputStream istream)
  {
    CustomerManagement.EmailMetrics value = new CustomerManagement.EmailMetrics ();
    value.campaignId = istream.read_string ();
    value.emailSent = istream.read_string ();
    value.emailDelivered = istream.read_string ();
    value.emailOpened = istream.read_string ();
    value.emailClicked = istream.read_string ();
    value.emailBounced = istream.read_string ();
    value.emailClickedThroughRate = istream.read_string ();
    value.emailConversionRate = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CustomerManagement.EmailMetrics value)
  {
    ostream.write_string (value.campaignId);
    ostream.write_string (value.emailSent);
    ostream.write_string (value.emailDelivered);
    ostream.write_string (value.emailOpened);
    ostream.write_string (value.emailClicked);
    ostream.write_string (value.emailBounced);
    ostream.write_string (value.emailClickedThroughRate);
    ostream.write_string (value.emailConversionRate);
  }

}
