package CustomerManagement;


/**
* CustomerManagement/EmailMarketingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public interface EmailMarketingServiceOperations 
{
  boolean createEmailCampaign (CustomerManagement.EmailCampaign campaign);
  boolean sendEmailCampaign (String campaignId);
  boolean scheduleEmailCampaign (String campaignId, String scheduleDate);
  boolean cancelEmailCampaign (String campaignId);
  CustomerManagement.EmailCampaign[] getAllEmailCampaigns ();
  CustomerManagement.EmailMetrics[] getEmailMetrics (String campaignId);
  String[] getEmailTargets (String campaignId);
  CustomerManagement.CustomerInfo[] getCustomersByTargets (String targetCustomer);
  boolean addCustomerToEmailTarget (String campaignId, String targetCustomer);
} // interface EmailMarketingServiceOperations
