package CustomerManagement;


/**
* CustomerManagement/SupportRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class SupportRequest implements org.omg.CORBA.portable.IDLEntity
{
  public String requestId = null;
  public String customerId = null;
  public String requestType = null;
  public String requestInfo = null;
  public String requestStatus = null;
  public String createdDate = null;
  public String updatedDate = null;
  public String resolutionDate = null;

  public SupportRequest ()
  {
  } // ctor

  public SupportRequest (String _requestId, String _customerId, String _requestType, String _requestInfo, String _requestStatus, String _createdDate, String _updatedDate, String _resolutionDate)
  {
    requestId = _requestId;
    customerId = _customerId;
    requestType = _requestType;
    requestInfo = _requestInfo;
    requestStatus = _requestStatus;
    createdDate = _createdDate;
    updatedDate = _updatedDate;
    resolutionDate = _resolutionDate;
  } // ctor

} // class SupportRequest
