package CustomerManagement;


/**
* CustomerManagement/TransactionInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class TransactionInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String transactionId = null;
  public String customerId = null;
  public String transactionInfo = null;
  public String transactionAmount = null;
  public String transactionType = null;
  public String paymentMethod = null;
  public String transactionDate = null;
  public String transactionStatus = null;

  public TransactionInfo ()
  {
  } // ctor

  public TransactionInfo (String _transactionId, String _customerId, String _transactionInfo, String _transactionAmount, String _transactionType, String _paymentMethod, String _transactionDate, String _transactionStatus)
  {
    transactionId = _transactionId;
    customerId = _customerId;
    transactionInfo = _transactionInfo;
    transactionAmount = _transactionAmount;
    transactionType = _transactionType;
    paymentMethod = _paymentMethod;
    transactionDate = _transactionDate;
    transactionStatus = _transactionStatus;
  } // ctor

} // class TransactionInfo
