package CustomerManagement;


/**
* CustomerManagement/UpdateHistoryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class UpdateHistoryListHolder implements org.omg.CORBA.portable.Streamable
{
  public CustomerManagement.UpdateHistory value[] = null;

  public UpdateHistoryListHolder ()
  {
  }

  public UpdateHistoryListHolder (CustomerManagement.UpdateHistory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CustomerManagement.UpdateHistoryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CustomerManagement.UpdateHistoryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CustomerManagement.UpdateHistoryListHelper.type ();
  }

}
