package CustomerManagement;

/**
* CustomerManagement/UpdateHistoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/java/cms/src/idl/CustomerManagement.idl
* Thursday, March 13, 2025 1:52:43 PM ICT
*/

public final class UpdateHistoryHolder implements org.omg.CORBA.portable.Streamable
{
  public CustomerManagement.UpdateHistory value = null;

  public UpdateHistoryHolder ()
  {
  }

  public UpdateHistoryHolder (CustomerManagement.UpdateHistory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CustomerManagement.UpdateHistoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CustomerManagement.UpdateHistoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CustomerManagement.UpdateHistoryHelper.type ();
  }

}
